//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace Widgets
{
	/// <summary>
	/// Represents a page of type <see cref="KnowMore"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class KnowMore : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Widgets.KnowMore";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// KnowMoreTitle.
		/// </summary>
		public string KnowMoreTitle { get; set; }


		/// <summary>
		/// KnowMoreDescription.
		/// </summary>
		public string KnowMoreDescription { get; set; }


		/// <summary>
		/// KnowMoreButtonName.
		/// </summary>
		public string KnowMoreButtonName { get; set; }


		/// <summary>
		/// KnowMoreButtonLink.
		/// </summary>
		public string KnowMoreButtonLink { get; set; }


		/// <summary>
		/// KnowMoreThumbnail.
		/// </summary>
		public IEnumerable<ImageAssets> KnowMoreThumbnail { get; set; }
	}
}