//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace Widgets
{
	/// <summary>
	/// Represents a page of type <see cref="ContentCards"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class ContentCards : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Widgets.ContentCards";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// ContentTitle.
		/// </summary>
		public string ContentTitle { get; set; }


		/// <summary>
		/// ContentSubTItle.
		/// </summary>
		public string ContentSubTItle { get; set; }


		/// <summary>
		/// ContentDescription.
		/// </summary>
		public string ContentDescription { get; set; }


		/// <summary>
		/// ContentButtonName.
		/// </summary>
		public string ContentButtonName { get; set; }


		/// <summary>
		/// ContentButtonLink.
		/// </summary>
		public string ContentButtonLink { get; set; }


		/// <summary>
		/// ContentBackgrounImage.
		/// </summary>
		public IEnumerable<ImageAssets> ContentBackgrounImage { get; set; }
	}
}